CI: CI- train and save model # 1. define pipeline name.
on:      # 2. define when it runs: event to trigger pipeline.
  push:  
    branches:[main]   # Run CI when code is pushed to main
  pull_request:     
    branches:[main]  # Run CI when a pull request is created to main

jobs:   # 3. Define job environment
  matrix_pip:
    name: Train and save model
    runs on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10,3.11,3.12]  # Test on multiple Python versions
    steps: # 5: Add steps to run the job
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses:actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name : upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name : install project dependencies
        run: python -m pip install -r requirements.txt

      - name: Train and save the model
        run : |
          python train.py
          ls -la artifacts   # model saved here 
      - name : upload artifacts
        uses :action/upload-artifcats@v4
        with:
        name: ml-artifacts -${{matrix-python}} -${{ github.run_id }} # name of artifact
        path : artifacts/  # path to the model artifacts





